# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyQualityControlToolkit
                                 A QGIS plugin
 A plugin to run geometry checks on vectorial polygon layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-05
        copyright            : (C) 2026 by Isaac Thompson
        email                : iswaldeen@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SurveyQualityControlToolkit class from file SurveyQualityControlToolkit.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .survey_quality_control_toolkit import SurveyQualityControlToolkit
    return SurveyQualityControlToolkit(iface)
