# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyQualityControlToolkit
                                 A QGIS plugin
 A plugin to run geometry checks on vectorial polygon layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Isaac Thompson
        email                : iswaldeen@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
import traceback
import webbrowser
from qgis.core import (
    QgsWkbTypes,
    QgsMessageLog,
    Qgis,
    QgsVectorLayer,
    QgsFeature
)
from .checks import (
    self_overlaps,
    multiple_reference_overlaps,
    difference_input_from_reference,
    linear_boundary_gaps
)
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .survey_quality_control_toolkit_dialog import SurveyQualityControlToolkitDialog
from .survey_quality_control_toolkit_dialog_settings import (
    SurveyQualityControlToolkitSettingsDialog
)
import os.path

CHECK_REGISTRY = {
    SurveyQualityControlToolkitDialog.CHECK_SELF_OVERLAPS: {
        "runner": self_overlaps.run,
        "requires_reference_layer": False,
        "success_message": (
            "No self-overlap errors were found "
            "in layer '{layer_name}'."
        ),
        "warning_message": (
            "Found {result_count} overlap polygon(s) "
            "in layer '{layer_name}'. "
            "Results added to "
            "'Survey Quality Checks/{layer_name}_self_overlaps'."
        ),
    },
    SurveyQualityControlToolkitDialog.CHECK_MULTI_REFERENCE_OVERLAPS: {
        "runner": multiple_reference_overlaps.run,
        "requires_reference_layer": True,
        "success_message": (
            "No multiple-reference overlap errors were found "
            "between '{layer_name}' and '{reference_layer_name}'."
        ),
        "warning_message": (
            "Found {result_count} multiple-reference overlap polygon(s) "
            "between '{layer_name}' and '{reference_layer_name}'. "
            "Results added to "
            "'Survey Quality Checks/"
            "{layer_name}_overlapping_multiple_{reference_layer_name}'."
        ),
    },
    SurveyQualityControlToolkitDialog.CHECK_DIFFERENCE_INPUT_FROM_REFERENCE: {
        "runner": difference_input_from_reference.run,
        "requires_reference_layer": True,
        "success_message": (
            "No difference areas were found between "
            "'{layer_name}' and '{reference_layer_name}'."
        ),
        "warning_message": (
            "Found {result_count} difference polygon(s) "
            "between '{layer_name}' and '{reference_layer_name}'. "
            "Results added to "
            "'Survey Quality Checks/"
            "{layer_name}_minus_{reference_layer_name}'."
        ),
    },
    SurveyQualityControlToolkitDialog.CHECK_LINEAR_BOUNDARY_GAPS: {
        "runner": linear_boundary_gaps.run,
        "requires_reference_layer": False,
        "success_message": (
            "No linear boundary gaps were found "
            "in layer '{layer_name}'."
        ),
        "warning_message": (
            "Found {result_count} linear boundary gap polygon(s) "
            "in layer '{layer_name}'. "
            "Results added to "
            "'Survey Quality Checks/{layer_name}_linear_boundary_gaps'."
        ),
    },
}
class SurveyQualityControlToolkit:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value(
            "locale/userLocale",
            "en"
        )

        locale = str(locale)[:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SurveyQualityControlToolkit_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Survey Quality Control Toolkit')
        self.dlg = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SurveyQualityControlToolkit', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action
    
    def theme_icon_path(self, light_icon_name, dark_icon_name):
        """
        Return the appropriate icon path for the current QGIS theme.
        """

        icon_name = (
            dark_icon_name
            if self.iface.mainWindow().palette().window().color().lightness() < 128
            else light_icon_name
        )

        return os.path.join(
            self.plugin_dir,
            "icons",
            icon_name
        )
    
    def open_help(self):
        """
        Open the plugin help page.
        """

        help_path = os.path.join(
            self.plugin_dir,
            "help",
            "help.html"
        )

        webbrowser.open(
            "file:///" + help_path.replace("\\", "/")
        )


    def open_settings(self):
        """
        Open the plugin settings dialog.
        """

        settings_dialog = SurveyQualityControlToolkitSettingsDialog(
            self.iface.mainWindow()
        )

        settings_dialog.exec()

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/survey_quality_control_toolkit/icons/sqc_toolkit_icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Survey Quality Control Toolkit'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        
        help_icon_path = self.theme_icon_path(
            "question_mark.png",
            "question_mark_darkmode.png"
        )

        self.add_action(
            help_icon_path,
            text=self.tr("Help"),
            callback=self.open_help,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        settings_icon_path = self.theme_icon_path(
            "settings.png",
            "settings_darkmode.png"
        )

        self.add_action(
            settings_icon_path,
            text=self.tr("Settings"),
            callback=self.open_settings,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Survey Quality Control Toolkit'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def show_success(self, message):
        """
        Show a success message using the configured duration.
        """

        settings = QSettings()

        duration = settings.value(
            "SurveyQualityControlToolkit/message_duration",
            10,
            type=int
        )

        self.iface.messageBar().pushMessage(
            "Survey Quality Control Toolkit",
            message,
            level=Qgis.Success,
            duration=duration
        )


    def show_warning(self, message):
        """
        Show a warning message using the configured duration.
        """

        settings = QSettings()

        duration = settings.value(
            "SurveyQualityControlToolkit/message_duration",
            10,
            type=int
        )

        self.iface.messageBar().pushMessage(
            "Survey Quality Control Toolkit",
            message,
            level=Qgis.Warning,
            duration=duration
        )
    
    def create_combined_reference_layer(self, reference_layers):
        """
        Combine selected reference polygon layers into one temporary layer.
        """

        if not reference_layers:
            raise ValueError("No reference layers supplied.")

        first_layer = reference_layers[0]
        crs = first_layer.crs()

        crs_uri = (
            crs.authid()
            if crs.isValid() and crs.authid()
            else crs.toWkt()
        )

        combined_layer = QgsVectorLayer(
            f"Polygon?crs={crs_uri}",
            "Combined Reference Layers",
            "memory"
        )

        provider = combined_layer.dataProvider()

        provider.addAttributes(
            first_layer.fields()
        )

        combined_layer.updateFields()

        output_features = []

        for reference_layer in reference_layers:

            for feature in reference_layer.getFeatures():

                new_feature = QgsFeature(
                    combined_layer.fields()
                )

                new_feature.setGeometry(
                    feature.geometry()
                )

                for field in combined_layer.fields():
                    field_name = field.name()

                    if field_name in feature.fields().names():
                        new_feature[field_name] = feature[field_name]

                output_features.append(
                    new_feature
                )

        provider.addFeatures(
            output_features
        )

        combined_layer.updateExtents()

        return combined_layer

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if not hasattr(self, "dlg") or self.dlg is None:
            self.dlg = SurveyQualityControlToolkitDialog(
                self.iface.mainWindow()
            )

        self.first_start = False

        if self.dlg.isVisible():

            self.dlg.raise_()
            self.dlg.activateWindow()

            return

        # Run the dialog event loop
        self.dlg.update_widget_states()
        result = self.dlg.exec()

        if not result:
            self.dlg.reset_dialog_state()
            return

        layer = self.dlg.layerComboBox.currentLayer()

        if not layer or not layer.isValid():

            self.show_warning(
                "Please select a valid layer."
            )

            return

        # Defensive check in case a non-polygon layer somehow reaches the tool.
        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:

            self.show_warning(
                "Selected layer is not a polygon layer."
            )

            return

        check_name = self.dlg.checkComboBox.currentText()

        reference_layers = (
            self.dlg.selected_reference_layers()
        )

        if not check_name:

            self.show_warning(
                "Please select a geometry check."
            )

            return

        try:
            check_config = CHECK_REGISTRY.get(check_name)

            if check_config is None:
                self.show_warning(
                    f"Unknown geometry check: {check_name}"
                )
                return

            requires_reference_layer = check_config["requires_reference_layer"]
            
            settings = QSettings()

            geometry_tolerance = settings.value(
                "SurveyQualityControlToolkit/geometry_tolerance",
                0.0,
                type=float
            )
            
            minimum_overlap_area = settings.value(
                "SurveyQualityControlToolkit/minimum_overlap_area",
                0.0001,
                type=float
            )

            minimum_difference_area = settings.value(
                "SurveyQualityControlToolkit/minimum_difference_area",
                0.01,
                type=float
            )

            gap_close_distance = settings.value(
                "SurveyQualityControlToolkit/gap_close_distance",
                0.005,
                type=float
            )
            
            reference_layer = None

            if check_name == SurveyQualityControlToolkitDialog.CHECK_SELF_OVERLAPS:

                result_count = check_config["runner"](
                    layer,
                    min_overlap_area=minimum_overlap_area
                )

            elif check_name == SurveyQualityControlToolkitDialog.CHECK_LINEAR_BOUNDARY_GAPS:

                result_count = check_config["runner"](
                    layer,
                    gap_close_dist=gap_close_distance
                )

            elif requires_reference_layer:

                if not reference_layers:

                    self.show_warning(
                        "Please select at least one valid reference layer."
                    )

                    return

                reference_layer = self.create_combined_reference_layer(
                    reference_layers
                )

                if check_name == SurveyQualityControlToolkitDialog.CHECK_MULTI_REFERENCE_OVERLAPS:

                    result_count = check_config["runner"](
                        layer,
                        reference_layer,
                        min_overlap_area=minimum_overlap_area,
                        tolerance=geometry_tolerance
                    )

                elif check_name == SurveyQualityControlToolkitDialog.CHECK_DIFFERENCE_INPUT_FROM_REFERENCE:

                    result_count = check_config["runner"](
                        layer,
                        reference_layer,
                        min_piece_area=minimum_difference_area,
                        tolerance=geometry_tolerance
                    )

                else:

                    self.show_warning(
                        f"Unsupported reference-layer check: {check_name}"
                    )

                    return

            else:

                self.show_warning(
                    f"Unsupported geometry check: {check_name}"
                )

                return

            reference_layer_name = (
                reference_layer.name()
                if reference_layer is not None
                else ""
            )

            success_message = check_config["success_message"].format(
                layer_name=layer.name(),
                reference_layer_name=reference_layer_name,
                result_count=result_count
            )

            warning_message = check_config["warning_message"].format(
                layer_name=layer.name(),
                reference_layer_name=reference_layer_name,
                result_count=result_count
            )
            
            if result_count == 0:

                self.show_success(
                    success_message
                )

            else:

                self.show_warning(
                    warning_message
                )
             
            self.dlg.reset_dialog_state()

        except Exception as e:

            QgsMessageLog.logMessage(
                traceback.format_exc(),
                "Survey Quality Control Toolkit",
                Qgis.Critical
            )

            self.show_warning(
                f"Error: {str(e)}"
            )